---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key

      - id: detect-aws-credentials
        name: detect aws credentials
        description: detects *your* aws credentials from the aws cli credentials file.
        entry: detect-aws-credentials
        language: python
        types: [text]

      - id: check-case-conflict

      - id: check-added-large-files
        args: ['--maxkb=1024']

      - id: mixed-line-ending
        args: ['--fix=lf']

      - id: end-of-file-fixer

      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      - id: check-json
        name: check json
        description: checks json files for parseable syntax.
        entry: check-json
        language: python
        types: [json]

      - id: check-toml
        name: check toml
        description: checks toml files for parseable syntax.
        entry: check-toml
        language: python
        types: [toml]

      - id: pretty-format-json
        args: ['--no-sort-keys', '--indent=4', '--no-ensure-ascii', '--autofix']

      - id: requirements-txt-fixer

      - id: check-symlinks
        name: check for broken symlinks
        description: checks for symlinks which do not point to anything.
        entry: check-symlinks
        language: python
        types: [symlink]

      - id: check-merge-conflict
        name: check for merge conflicts
        description: checks for files that contain merge conflict strings.
        entry: check-merge-conflict
        language: python
        types: [text]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [--strict, -c=./.yamllint]
